# Generated by Django 5.0.2 on 2024-02-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
