# Generated by Django 5.0.2 on 2024-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
